name: moor_db_viewer
description: A package to view your moor database in your own app with filtering and without the need of exporting your db file.
version: 3.1.0
homepage: https://github.com/vanlooverenkoen/moor_db_viewer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor: ^4.3.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
